//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFTriadBuddy.loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFTriadBuddy.loc.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AdjustForm_CancelButton {
            get {
                return ResourceManager.GetString("AdjustForm_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:.
        /// </summary>
        internal static string AdjustForm_CardDown {
            get {
                return ResourceManager.GetString("AdjustForm_CardDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:.
        /// </summary>
        internal static string AdjustForm_CardLeft {
            get {
                return ResourceManager.GetString("AdjustForm_CardLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted:.
        /// </summary>
        internal static string AdjustForm_CardList {
            get {
                return ResourceManager.GetString("AdjustForm_CardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R:.
        /// </summary>
        internal static string AdjustForm_CardRight {
            get {
                return ResourceManager.GetString("AdjustForm_CardRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string AdjustForm_CardStatus {
            get {
                return ResourceManager.GetString("AdjustForm_CardStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U:.
        /// </summary>
        internal static string AdjustForm_CardUp {
            get {
                return ResourceManager.GetString("AdjustForm_CardUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current:.
        /// </summary>
        internal static string AdjustForm_Current {
            get {
                return ResourceManager.GetString("AdjustForm_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance:.
        /// </summary>
        internal static string AdjustForm_Distance {
            get {
                return ResourceManager.GetString("AdjustForm_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto.
        /// </summary>
        internal static string AdjustForm_Dynamic_Digit_Default {
            get {
                return ResourceManager.GetString("AdjustForm_Dynamic_Digit_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom.
        /// </summary>
        internal static string AdjustForm_Dynamic_Digit_Override {
            get {
                return ResourceManager.GetString("AdjustForm_Dynamic_Digit_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;= Classifier based.
        /// </summary>
        internal static string AdjustForm_Dynamic_Distance_Classifier {
            get {
                return ResourceManager.GetString("AdjustForm_Dynamic_Distance_Classifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;= Lower is more accurate.
        /// </summary>
        internal static string AdjustForm_Dynamic_Distance_DefaultHint {
            get {
                return ResourceManager.GetString("AdjustForm_Dynamic_Distance_DefaultHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;= Exact match.
        /// </summary>
        internal static string AdjustForm_Dynamic_Distance_Exact {
            get {
                return ResourceManager.GetString("AdjustForm_Dynamic_Distance_Exact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string AdjustForm_Dynamic_Distance_NotAvail {
            get {
                return ResourceManager.GetString("AdjustForm_Dynamic_Distance_NotAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string AdjustForm_Dynamic_UnknownOwner {
            get {
                return ResourceManager.GetString("AdjustForm_Dynamic_UnknownOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect:.
        /// </summary>
        internal static string AdjustForm_HashList {
            get {
                return ResourceManager.GetString("AdjustForm_HashList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AdjustForm_SaveButton {
            get {
                return ResourceManager.GetString("AdjustForm_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust detection.
        /// </summary>
        internal static string AdjustForm_Title {
            get {
                return ResourceManager.GetString("AdjustForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF Triad Buddy.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock card for deck optimization.
        /// </summary>
        internal static string DeckCtrl_CtxMenu_LockForOptimization {
            get {
                return ResourceManager.GetString("DeckCtrl_CtxMenu_LockForOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick card:.
        /// </summary>
        internal static string DeckCtrl_CtxMenu_PickCard {
            get {
                return ResourceManager.GetString("DeckCtrl_CtxMenu_PickCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use only owned cards (click to change).
        /// </summary>
        internal static string DeckCtrl_CtxMenu_UseOnlyOwned {
            get {
                return ResourceManager.GetString("DeckCtrl_CtxMenu_UseOnlyOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string FavDeckCtrl_Edit {
            get {
                return ResourceManager.GetString("FavDeckCtrl_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string FavDeckForm_AddButton {
            get {
                return ResourceManager.GetString("FavDeckForm_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fav #{0}.
        /// </summary>
        internal static string FavDeckForm_Dynamic_AutoName {
            get {
                return ResourceManager.GetString("FavDeckForm_Dynamic_AutoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite deck will be removed, do you want to continue?.
        /// </summary>
        internal static string FavDeckForm_Dynamic_RemoveMsg {
            get {
                return ResourceManager.GetString("FavDeckForm_Dynamic_RemoveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string FavDeckForm_Dynamic_UpdateButton {
            get {
                return ResourceManager.GetString("FavDeckForm_Dynamic_UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite deck, click card for options:.
        /// </summary>
        internal static string FavDeckForm_Info {
            get {
                return ResourceManager.GetString("FavDeckForm_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name:.
        /// </summary>
        internal static string FavDeckForm_Name {
            get {
                return ResourceManager.GetString("FavDeckForm_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string FavDeckForm_RemoveButton {
            get {
                return ResourceManager.GetString("FavDeckForm_RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit favorite deck.
        /// </summary>
        internal static string FavDeckForm_Title {
            get {
                return ResourceManager.GetString("FavDeckForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffxiv_dx11.
        /// </summary>
        internal static string Game_ProcessName_DX11 {
            get {
                return ResourceManager.GetString("Game_ProcessName_DX11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffxiv.
        /// </summary>
        internal static string Game_ProcessName_DX9 {
            get {
                return ResourceManager.GetString("Game_ProcessName_DX9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINAL FANTASY.
        /// </summary>
        internal static string Game_WindowNamePrefix {
            get {
                return ResourceManager.GetString("Game_WindowNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        internal static string MainForm_Cards_IconsTitle {
            get {
                return ResourceManager.GetString("MainForm_Cards_IconsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string MainForm_Cards_List_ColumnId {
            get {
                return ResourceManager.GetString("MainForm_Cards_List_ColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string MainForm_Cards_List_ColumnName {
            get {
                return ResourceManager.GetString("MainForm_Cards_List_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned.
        /// </summary>
        internal static string MainForm_Cards_List_ColumnOwned {
            get {
                return ResourceManager.GetString("MainForm_Cards_List_ColumnOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string MainForm_Cards_List_ColumnPower {
            get {
                return ResourceManager.GetString("MainForm_Cards_List_ColumnPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity.
        /// </summary>
        internal static string MainForm_Cards_List_ColumnRarity {
            get {
                return ResourceManager.GetString("MainForm_Cards_List_ColumnRarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string MainForm_Cards_List_ColumnType {
            get {
                return ResourceManager.GetString("MainForm_Cards_List_ColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string MainForm_Cards_ListTitle {
            get {
                return ResourceManager.GetString("MainForm_Cards_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of owned cards:.
        /// </summary>
        internal static string MainForm_Cards_NumOwned {
            get {
                return ResourceManager.GetString("MainForm_Cards_NumOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        internal static string MainForm_Cards_Title {
            get {
                return ResourceManager.GetString("MainForm_Cards_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find online.
        /// </summary>
        internal static string MainForm_CtxMenu_CardInfo_FindOnline {
            get {
                return ResourceManager.GetString("MainForm_CtxMenu_CardInfo_FindOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Npc reward:.
        /// </summary>
        internal static string MainForm_CtxMenu_CardInfo_NpcReward {
            get {
                return ResourceManager.GetString("MainForm_CtxMenu_CardInfo_NpcReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find card:.
        /// </summary>
        internal static string MainForm_CtxMenu_FindCard {
            get {
                return ResourceManager.GetString("MainForm_CtxMenu_FindCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find npc:.
        /// </summary>
        internal static string MainForm_CtxMenu_FindNpc {
            get {
                return ResourceManager.GetString("MainForm_CtxMenu_FindNpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust....
        /// </summary>
        internal static string MainForm_CtxMenu_Learn_Adjust {
            get {
                return ResourceManager.GetString("MainForm_CtxMenu_Learn_Adjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string MainForm_CtxMenu_Learn_Delete {
            get {
                return ResourceManager.GetString("MainForm_CtxMenu_Learn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewards (click to add/remove).
        /// </summary>
        internal static string MainForm_CtxMenu_SelectNpc_Rewards {
            get {
                return ResourceManager.GetString("MainForm_CtxMenu_SelectNpc_Rewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select npc to play.
        /// </summary>
        internal static string MainForm_CtxMenu_SelectNpc_Select {
            get {
                return ResourceManager.GetString("MainForm_CtxMenu_SelectNpc_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MainForm_Dynamic_CardOwnedColumn {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_CardOwnedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found duplicate cards!.
        /// </summary>
        internal static string MainForm_Dynamic_DeckState_HasDuplicates {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_DeckState_HasDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing cards!.
        /// </summary>
        internal static string MainForm_Dynamic_DeckState_MissingCards {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_DeckState_MissingCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than two 4+ star!.
        /// </summary>
        internal static string MainForm_Dynamic_DeckState_TooMany4Star {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_DeckState_TooMany4Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one 5 star allowed!.
        /// </summary>
        internal static string MainForm_Dynamic_DeckState_TooMany5Star {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_DeckState_TooMany5Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MainForm_Dynamic_NpcCompletedColumn {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_NpcCompletedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string MainForm_Dynamic_RuleListEmpty {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_RuleListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string MainForm_Dynamic_Screenhot_Status_NoErrors {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenhot_Status_NoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bot.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_BoardRow_Bottom {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_BoardRow_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mid.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_BoardRow_Middle {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_BoardRow_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_BoardRow_Top {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_BoardRow_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue {0}.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_CardLocation_BlueDeck {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_CardLocation_BlueDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board {0} {1}.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_CardLocation_Board {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_CardLocation_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red {0}.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_CardLocation_RedDeck {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_CardLocation_RedDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not detected!.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_CardNotDetected {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_CardNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_HashType_Card {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_HashType_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_HashType_Number {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_HashType_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_HashType_Rule {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_HashType_Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_MatchType_Auto {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_MatchType_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_MatchType_Exact {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_MatchType_Exact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_MatchType_Similar {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_MatchType_Similar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (select match).
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_SelectDetectionMatch {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_SelectDetectionMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_Status_Disabled {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_Status_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to recognize some of cards! Game state won&apos;t be accurate.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_Status_FailedCardMatching {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_Status_FailedCardMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find board! Try resetting UI position, turning off reshade, etc....
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_Status_MissingGridOrCards {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_Status_MissingGridOrCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t recognize pattern! See details below.
        /// </summary>
        internal static string MainForm_Dynamic_Screenshot_Status_UnknownHash {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Screenshot_Status_UnknownHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud save applied.
        /// </summary>
        internal static string MainForm_Dynamic_Setup_CloudSave_Loaded {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Setup_CloudSave_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API call failed.
        /// </summary>
        internal static string MainForm_Dynamic_Setup_CloudStatus_ApiFailure {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Setup_CloudStatus_ApiFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorizing....
        /// </summary>
        internal static string MainForm_Dynamic_Setup_CloudStatus_AuthInProgress {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Setup_CloudStatus_AuthInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled, local only.
        /// </summary>
        internal static string MainForm_Dynamic_Setup_CloudStatus_Disabled {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Setup_CloudStatus_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database failure.
        /// </summary>
        internal static string MainForm_Dynamic_Setup_CloudStatus_NoDatabase {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Setup_CloudStatus_NoDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        internal static string MainForm_Dynamic_Setup_CloudStatus_NoErrors {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Setup_CloudStatus_NoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth required.
        /// </summary>
        internal static string MainForm_Dynamic_Setup_CloudStatus_NotAuthorized {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Setup_CloudStatus_NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scanning....
        /// </summary>
        internal static string MainForm_Dynamic_Setup_CloudStatus_NotInitialized {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Setup_CloudStatus_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to synchronized.
        /// </summary>
        internal static string MainForm_Dynamic_Setup_CloudStatus_Synced {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Setup_CloudStatus_Synced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stored.
        /// </summary>
        internal static string MainForm_Dynamic_Setup_CloudStatus_Uploaded {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Setup_CloudStatus_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aborted at {0:P0}.
        /// </summary>
        internal static string MainForm_Dynamic_Setup_OptimizerProgressAborted {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Setup_OptimizerProgressAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue starts.
        /// </summary>
        internal static string MainForm_Dynamic_Simulate_BlueStartButton {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Simulate_BlueStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (DRAW).
        /// </summary>
        internal static string MainForm_Dynamic_Simulate_ChanceIsDraw {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Simulate_ChanceIsDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to change card.
        /// </summary>
        internal static string MainForm_Dynamic_Simulate_ChangeBlueHint {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Simulate_ChangeBlueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draw.
        /// </summary>
        internal static string MainForm_Dynamic_Simulate_EndGame_BlueDraw {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Simulate_EndGame_BlueDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lost.
        /// </summary>
        internal static string MainForm_Dynamic_Simulate_EndGame_BlueLost {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Simulate_EndGame_BlueLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yay!.
        /// </summary>
        internal static string MainForm_Dynamic_Simulate_EndGame_BlueWin {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Simulate_EndGame_BlueWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Place last red card to trigger modifier].
        /// </summary>
        internal static string MainForm_Dynamic_Simulate_LastCardHint {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Simulate_LastCardHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red start: drag &amp;&amp; drop card on board.
        /// </summary>
        internal static string MainForm_Dynamic_Simulate_RedStartButton {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Simulate_RedStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one card from each deck to swap.
        /// </summary>
        internal static string MainForm_Dynamic_Simulate_SwapRuleButton {
            get {
                return ResourceManager.GetString("MainForm_Dynamic_Simulate_SwapRuleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string MainForm_Npcs_List_ColumnCompleted {
            get {
                return ResourceManager.GetString("MainForm_Npcs_List_ColumnCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string MainForm_Npcs_List_ColumnLocation {
            get {
                return ResourceManager.GetString("MainForm_Npcs_List_ColumnLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string MainForm_Npcs_List_ColumnName {
            get {
                return ResourceManager.GetString("MainForm_Npcs_List_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string MainForm_Npcs_List_ColumnPower {
            get {
                return ResourceManager.GetString("MainForm_Npcs_List_ColumnPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward.
        /// </summary>
        internal static string MainForm_Npcs_List_ColumnReward {
            get {
                return ResourceManager.GetString("MainForm_Npcs_List_ColumnReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string MainForm_Npcs_List_ColumnRules {
            get {
                return ResourceManager.GetString("MainForm_Npcs_List_ColumnRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of npcs with cards:.
        /// </summary>
        internal static string MainForm_Npcs_NumKnown {
            get {
                return ResourceManager.GetString("MainForm_Npcs_NumKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Npcs.
        /// </summary>
        internal static string MainForm_Npcs_Title {
            get {
                return ResourceManager.GetString("MainForm_Npcs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current state:.
        /// </summary>
        internal static string MainForm_Screenshot_CurrentState {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_CurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last detection.
        /// </summary>
        internal static string MainForm_Screenshot_History_CardsColumnDetection {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_History_CardsColumnDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers [U-L-D-R].
        /// </summary>
        internal static string MainForm_Screenshot_History_CardsColumnSides {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_History_CardsColumnSides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string MainForm_Screenshot_History_CardsColumnType {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_History_CardsColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last detection.
        /// </summary>
        internal static string MainForm_Screenshot_History_HashColumnDetection {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_History_HashColumnDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string MainForm_Screenshot_History_HashColumnType {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_History_HashColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules:
        ///- game must be in Windowed or Borderless Windowed mode
        ///- UI: set scale to 100%, use dark scheme
        ///- npc must be selected
        ///- capture during Blue turn, after all card animations finished (!!!)
        ///
        ///Gamepad: press both trigger buttons to capture
        ///
        ///Works with Mini Cactpot too :D.
        /// </summary>
        internal static string MainForm_Screenshot_InfoLines {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_InfoLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect:.
        /// </summary>
        internal static string MainForm_Screenshot_Learn_DetectList {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_Learn_DetectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard All.
        /// </summary>
        internal static string MainForm_Screenshot_Learn_DiscardAllButton {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_Learn_DiscardAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Resets scanner state.
        /// </summary>
        internal static string MainForm_Screenshot_Learn_DiscardAllInfo {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_Learn_DiscardAllInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (there are {0} more pending).
        /// </summary>
        internal static string MainForm_Screenshot_Learn_PendingPlural {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_Learn_PendingPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (there is 1 more pending).
        /// </summary>
        internal static string MainForm_Screenshot_Learn_PendingSingular {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_Learn_PendingSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string MainForm_Screenshot_Learn_SaveButton {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_Learn_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source image:.
        /// </summary>
        internal static string MainForm_Screenshot_Learn_SourceImage {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_Learn_SourceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string MainForm_Screenshot_Learn_Type {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_Learn_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^ Right click on lists for options.
        /// </summary>
        internal static string MainForm_Screenshot_ListHint {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_ListHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove local patterns.
        /// </summary>
        internal static string MainForm_Screenshot_RemovePatternsButton {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_RemovePatternsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use to clear all custom patterns and start from scratch:.
        /// </summary>
        internal static string MainForm_Screenshot_RemovePatternsTitle {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_RemovePatternsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play: Screenshot.
        /// </summary>
        internal static string MainForm_Screenshot_Title {
            get {
                return ResourceManager.GetString("MainForm_Screenshot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        internal static string MainForm_Setup_Cloud_AuthButton {
            get {
                return ResourceManager.GetString("MainForm_Setup_Cloud_AuthButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save in Google:.
        /// </summary>
        internal static string MainForm_Setup_Cloud_Desc {
            get {
                return ResourceManager.GetString("MainForm_Setup_Cloud_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string MainForm_Setup_Deck_OptimizeAbortButton {
            get {
                return ResourceManager.GetString("MainForm_Setup_Deck_OptimizeAbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize deck for NPC.
        /// </summary>
        internal static string MainForm_Setup_Deck_OptimizeStartButton {
            get {
                return ResourceManager.GetString("MainForm_Setup_Deck_OptimizeStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active deck, click card for options:.
        /// </summary>
        internal static string MainForm_Setup_Deck_Title {
            get {
                return ResourceManager.GetString("MainForm_Setup_Deck_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add favorite deck slot.
        /// </summary>
        internal static string MainForm_Setup_Fav_AddSlotButton {
            get {
                return ResourceManager.GetString("MainForm_Setup_Fav_AddSlotButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC:.
        /// </summary>
        internal static string MainForm_Setup_NPC {
            get {
                return ResourceManager.GetString("MainForm_Setup_NPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck power:.
        /// </summary>
        internal static string MainForm_Setup_NPC_DeckPower {
            get {
                return ResourceManager.GetString("MainForm_Setup_NPC_DeckPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string MainForm_Setup_NPC_Location {
            get {
                return ResourceManager.GetString("MainForm_Setup_NPC_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules:.
        /// </summary>
        internal static string MainForm_Setup_NPC_Rules {
            get {
                return ResourceManager.GetString("MainForm_Setup_NPC_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win chance:.
        /// </summary>
        internal static string MainForm_Setup_NPC_WinChance {
            get {
                return ResourceManager.GetString("MainForm_Setup_NPC_WinChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num owned cards:.
        /// </summary>
        internal static string MainForm_Setup_OptimizerStats_NumOwned {
            get {
                return ResourceManager.GetString("MainForm_Setup_OptimizerStats_NumOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num possible decks:.
        /// </summary>
        internal static string MainForm_Setup_OptimizerStats_NumPossible {
            get {
                return ResourceManager.GetString("MainForm_Setup_OptimizerStats_NumPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num tested decks:.
        /// </summary>
        internal static string MainForm_Setup_OptimizerStats_NumTested {
            get {
                return ResourceManager.GetString("MainForm_Setup_OptimizerStats_NumTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress:.
        /// </summary>
        internal static string MainForm_Setup_OptimizerStats_Progress {
            get {
                return ResourceManager.GetString("MainForm_Setup_OptimizerStats_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time left:.
        /// </summary>
        internal static string MainForm_Setup_OptimizerStats_TimeLeft {
            get {
                return ResourceManager.GetString("MainForm_Setup_OptimizerStats_TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimization stats:.
        /// </summary>
        internal static string MainForm_Setup_OptimizeStats_Title {
            get {
                return ResourceManager.GetString("MainForm_Setup_OptimizeStats_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region rule 1:.
        /// </summary>
        internal static string MainForm_Setup_Rules_Region1 {
            get {
                return ResourceManager.GetString("MainForm_Setup_Rules_Region1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region rule 2:.
        /// </summary>
        internal static string MainForm_Setup_Rules_Region2 {
            get {
                return ResourceManager.GetString("MainForm_Setup_Rules_Region2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament:.
        /// </summary>
        internal static string MainForm_Setup_Rules_Tournament {
            get {
                return ResourceManager.GetString("MainForm_Setup_Rules_Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules:.
        /// </summary>
        internal static string MainForm_Setup_Rules_TournamentRules {
            get {
                return ResourceManager.GetString("MainForm_Setup_Rules_TournamentRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle npc rules, disable for tournament.
        /// </summary>
        internal static string MainForm_Setup_RulesToggle {
            get {
                return ResourceManager.GetString("MainForm_Setup_RulesToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string MainForm_Setup_Title {
            get {
                return ResourceManager.GetString("MainForm_Setup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force using cached image.
        /// </summary>
        internal static string MainForm_Simulate_Debug_ForceCached {
            get {
                return ResourceManager.GetString("MainForm_Simulate_Debug_ForceCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take game screenshot: DEBUG mode.
        /// </summary>
        internal static string MainForm_Simulate_Debug_Info {
            get {
                return ResourceManager.GetString("MainForm_Simulate_Debug_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply rule.
        /// </summary>
        internal static string MainForm_Simulate_Game_ApplyRuleButton {
            get {
                return ResourceManager.GetString("MainForm_Simulate_Game_ApplyRuleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Drag &amp;&amp; drop cards on board].
        /// </summary>
        internal static string MainForm_Simulate_Game_ListHint {
            get {
                return ResourceManager.GetString("MainForm_Simulate_Game_ListHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Rule &gt;&gt;.
        /// </summary>
        internal static string MainForm_Simulate_Game_SpecialRule {
            get {
                return ResourceManager.GetString("MainForm_Simulate_Game_SpecialRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust randomized deck :(.
        /// </summary>
        internal static string MainForm_Simulate_Random_Info {
            get {
                return ResourceManager.GetString("MainForm_Simulate_Random_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string MainForm_Simulate_ResetButton {
            get {
                return ResourceManager.GetString("MainForm_Simulate_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick roulette rule #1.
        /// </summary>
        internal static string MainForm_Simulate_Roulette_Rule1 {
            get {
                return ResourceManager.GetString("MainForm_Simulate_Roulette_Rule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick roulette rule #2.
        /// </summary>
        internal static string MainForm_Simulate_Roulette_Rule2 {
            get {
                return ResourceManager.GetString("MainForm_Simulate_Roulette_Rule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick roulette rule #3.
        /// </summary>
        internal static string MainForm_Simulate_Roulette_Rule3 {
            get {
                return ResourceManager.GetString("MainForm_Simulate_Roulette_Rule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick roulette rule #4.
        /// </summary>
        internal static string MainForm_Simulate_Roulette_Rule4 {
            get {
                return ResourceManager.GetString("MainForm_Simulate_Roulette_Rule4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current rules:.
        /// </summary>
        internal static string MainForm_Simulate_RuleList {
            get {
                return ResourceManager.GetString("MainForm_Simulate_RuleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play: Simulate.
        /// </summary>
        internal static string MainForm_Simulate_Title {
            get {
                return ResourceManager.GetString("MainForm_Simulate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo last Red move.
        /// </summary>
        internal static string MainForm_Simulate_UndoRedMoveButton {
            get {
                return ResourceManager.GetString("MainForm_Simulate_UndoRedMoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win chance:.
        /// </summary>
        internal static string MainForm_Simulate_WinChance {
            get {
                return ResourceManager.GetString("MainForm_Simulate_WinChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version downloaded, please restart program to finish update. Click here to hide..
        /// </summary>
        internal static string MainForm_UpdateNotify {
            get {
                return ResourceManager.GetString("MainForm_UpdateNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto scan.
        /// </summary>
        internal static string OverlayForm_Capture_AutoScan {
            get {
                return ResourceManager.GetString("OverlayForm_Capture_AutoScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        internal static string OverlayForm_Capture_Button {
            get {
                return ResourceManager.GetString("OverlayForm_Capture_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        internal static string OverlayForm_Capture_Details {
            get {
                return ResourceManager.GetString("OverlayForm_Capture_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string OverlayForm_Capture_Status {
            get {
                return ResourceManager.GetString("OverlayForm_Capture_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWAPPED.
        /// </summary>
        internal static string OverlayForm_CardInfo_Swapped {
            get {
                return ResourceManager.GetString("OverlayForm_CardInfo_Swapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue deck is not matching Setup page! Solver needs to observe a few games to guess correct one..
        /// </summary>
        internal static string OverlayForm_DeckInfo_Mismatch {
            get {
                return ResourceManager.GetString("OverlayForm_DeckInfo_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC: {0}.
        /// </summary>
        internal static string OverlayForm_Details_Npc {
            get {
                return ResourceManager.GetString("OverlayForm_Details_Npc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red deck details:.
        /// </summary>
        internal static string OverlayForm_Details_RedDeck {
            get {
                return ResourceManager.GetString("OverlayForm_Details_RedDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Potential red cards, not including visible ones below:.
        /// </summary>
        internal static string OverlayForm_Details_RedInfo {
            get {
                return ResourceManager.GetString("OverlayForm_Details_RedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All placed: {0}.
        /// </summary>
        internal static string OverlayForm_Details_RedPlacedAll {
            get {
                return ResourceManager.GetString("OverlayForm_Details_RedPlacedAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Var placed: {0}.
        /// </summary>
        internal static string OverlayForm_Details_RedPlacedVariable {
            get {
                return ResourceManager.GetString("OverlayForm_Details_RedPlacedVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules: {0}.
        /// </summary>
        internal static string OverlayForm_Details_Rules {
            get {
                return ResourceManager.GetString("OverlayForm_Details_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Id: {0}.
        /// </summary>
        internal static string OverlayForm_Details_ScanId {
            get {
                return ResourceManager.GetString("OverlayForm_Details_ScanId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string OverlayForm_Dynamic_NpcUnknown {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_NpcUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to npc changed, waiting for scan....
        /// </summary>
        internal static string OverlayForm_Dynamic_RulesWaiting {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_RulesWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready (active turn!).
        /// </summary>
        internal static string OverlayForm_Dynamic_Status_ActiveTurn {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_Status_ActiveTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move cursor away from scan zone!.
        /// </summary>
        internal static string OverlayForm_Dynamic_Status_AutoScanMouseOverBoard {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_Status_AutoScanMouseOverBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini cactpot: Ready.
        /// </summary>
        internal static string OverlayForm_Dynamic_Status_CactpotReady {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_Status_CactpotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown cards! Check Play:Screenshot for details.
        /// </summary>
        internal static string OverlayForm_Dynamic_Status_FailedCardMatching {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_Status_FailedCardMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find blue deck.
        /// </summary>
        internal static string OverlayForm_Dynamic_Status_MissingCards {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_Status_MissingCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is not running.
        /// </summary>
        internal static string OverlayForm_Dynamic_Status_MissingGameProcess {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_Status_MissingGameProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find game window.
        /// </summary>
        internal static string OverlayForm_Dynamic_Status_MissingGameWindow {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_Status_MissingGameWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find board.
        /// </summary>
        internal static string OverlayForm_Dynamic_Status_MissingGrid {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_Status_MissingGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t retrieve image to analyze.
        /// </summary>
        internal static string OverlayForm_Dynamic_Status_NoInputImage {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_Status_NoInputImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find minigame window.
        /// </summary>
        internal static string OverlayForm_Dynamic_Status_NoScannerMatch {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_Status_NoScannerMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string OverlayForm_Dynamic_Status_Ready {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to recognize minigame.
        /// </summary>
        internal static string OverlayForm_Dynamic_Status_ScannerErrors {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_Status_ScannerErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown pattern! Check Play:Screenshot for details.
        /// </summary>
        internal static string OverlayForm_Dynamic_Status_UnknownHash {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_Status_UnknownHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for blue turn.
        /// </summary>
        internal static string OverlayForm_Dynamic_Status_WaitingForTurn {
            get {
                return ResourceManager.GetString("OverlayForm_Dynamic_Status_WaitingForTurn", resourceCulture);
            }
        }
    }
}
